Resources:
  RoleForAPIDestination:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
        Version: "2012-10-17"
      Description: Role to provide access to API Destination
      RoleName: qualys-ssm-event-bridge-role
      Tags:
        - Key: App
          Value: qualys-ssm-based-assessment
  PolicyAPIBased:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - events:InvokeApiDestination
              - events:PutEvents
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: qualys-ssm-event-bridge-policy
      Roles:
        - Ref: RoleForAPIDestination
  StackSetAdministrationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
        Version: "2012-10-17"
      Policies:
        - PolicyDocument:
            Statement:
              - Action: sts:AssumeRole
                Effect: Allow
                Resource:
                  Fn::Join:
                    - ""
                    - - "arn:aws:iam::"
                      - Ref: AWS::AccountId
                      - :role/qualys-ssm-stack-execution-role
            Version: "2012-10-17"
          PolicyName: assumeExecutionRolePolicy
      RoleName: qualys-ssm-stack-administration-role
      Tags:
        - Key: App
          Value: qualys-ssm-based-assessment
  StackSetExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                Fn::GetAtt:
                  - StackSetAdministrationRole
                  - Arn
        Version: "2012-10-17"
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - cloudformation:*
                  - events:*
                  - secretsmanager:*
                Effect: Allow
                Resource: "*"
              - Action: iam:PassRole
                Effect: Allow
                Resource:
                  Fn::GetAtt:
                    - RoleForAPIDestination
                    - Arn
            Version: "2012-10-17"
          PolicyName: stackExecutionPolicy
      RoleName: qualys-ssm-stack-execution-role
      Tags:
        - Key: App
          Value: qualys-ssm-based-assessment
  APIConnection:
    Type: AWS::Events::Connection
    Properties:
      AuthParameters:
        ApiKeyAuthParameters:
          ApiKeyName: X-API-KEY
          ApiKeyValue: QFLOW-SSM-EVALUATION
        InvocationHttpParameters:
          HeaderParameters:
            - IsValueSecret: false
              Key: Authorization
              Value:
                Fn::Join:
                  - " "
                  - - Bearer
                    - Ref: SubscriptionToken
      AuthorizationType: API_KEY
      Description: Connection for Qualys Zero-Touch API Based Assessment
      Name: qualys-ssm-api-connection
  APIDestinationApiDestination:
    Type: AWS::Events::ApiDestination
    Properties:
      ConnectionArn:
        Fn::GetAtt:
          - APIConnection
          - Arn
      Description: API Destination for Qualys Zero-Touch API Based Assessment
      HttpMethod: POST
      InvocationEndpoint:
        Fn::Join:
          - /
          - - Ref: APIGatewayURL
            - qflow/aws-eb
      InvocationRateLimitPerSecond: 300
      Name: qualys-ssm-api-destination
  EventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: EventBridge rule which listens to ec2 running state and sends event to qualys
      EventBusName: default
      EventPattern:
        source:
          - aws.ec2
        detail-type:
          - EC2 Instance State-change Notification
        detail:
          state:
            - running
      Name: qualys-ssm-event-rule
      State: ENABLED
      Targets:
        - Arn:
            Fn::GetAtt:
              - APIDestinationApiDestination
              - Arn
          Id: Target0
          RoleArn:
            Fn::Join:
              - ":"
              - - "arn:aws:iam:"
                - Ref: AWS::AccountId
                - role/qualys-ssm-event-bridge-role
  RegionStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      AdministrationRoleARN:
        Fn::GetAtt:
          - StackSetAdministrationRole
          - Arn
      Description: deploys event bridge across multiple regions
      ExecutionRoleName:
        Ref: StackSetExecutionRole
      OperationPreferences:
        RegionConcurrencyType: PARALLEL
      Parameters:
        - ParameterKey: MainEventBridgeRegion
          ParameterValue:
            Ref: AWS::Region
      PermissionModel: SELF_MANAGED
      StackInstancesGroup:
        - DeploymentTargets:
            Accounts:
              - Ref: AWS::AccountId
          Regions:
            Ref: Regions
      StackSetName: qualys-ssm-cross-region
      Tags:
        - Key: App
          Value: qualys-ssm-based-assessment
      TemplateBody: |+
        {
          "Parameters": {
            "MainEventBridgeRegion": {
              "Type": "String"
            }
          },
          "Conditions": {
            "NotRegionCondition": {
              "Fn::Not": [
                {
                  "Fn::Equals": [
                    {
                      "Ref": "AWS::Region"
                    },
                    {
                      "Ref": "MainEventBridgeRegion"
                    }
                  ]
                }
              ]
            }
          },
          "Resources": {
            "CrossRegionEventRule": {
              "Type": "AWS::Events::Rule",
              "Properties": {
                "Description": "EventBridge rule which listens to ec2 running state on this specific region and forwards it to the main region",
                "EventBusName": "default",
                "EventPattern": {
                  "source": [
                    "aws.ec2"
                  ],
                  "detail-type": [
                    "EC2 Instance State-change Notification"
                  ],
                  "detail": {
                    "state": [
                      "running"
                    ]
                  }
                },
                "Name": "qualys-ssm-event-rule",
                "State": "ENABLED",
                "Targets": [
                  {
                    "Arn": {
                      "Fn::Join": [
                        "",
                        [
                          "arn:aws:events:",
                          {
                            "Ref": "MainEventBridgeRegion"
                          },
                          ":",
                          {
                            "Ref": "AWS::AccountId"
                          },
                          ":event-bus/default"
                        ]
                      ]
                    },
                    "Id": "Target0",
                    "RoleArn": {
                      "Fn::Join": [
                        ":",
                        [
                          "arn:aws:iam:",
                          {
                            "Ref": "AWS::AccountId"
                          },
                          "role/qualys-ssm-event-bridge-role"
                        ]
                      ]
                    }
                  }
                ]
              },
              "Condition": "NotRegionCondition"
            }
          }
        }

    DependsOn:
      - RoleForAPIDestination
Parameters:
  SubscriptionToken:
    Type: String
    Default:
    AllowedPattern: ^[\w\-]{1,64}\.[\w\-]{1,1024}\.[\w\-]{20,100}$
    ConstraintDescription: Token should match the given constraint.
    Description: Follow the steps mentioned in UserGuide to generate SubscriptionToken :- https://docs.qualys.com/en/conn/latest/#t=scans%2Fsnapshot-based_scan.htm
    MinLength: 1
    NoEcho: true
  APIGatewayURL:
    Type: String
    Default:
    AllowedPattern: ^(http(s):\/\/.)[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)$
    ConstraintDescription: It should be a valid URL.
    Description: Qualys API Gateway URL. Find the Gateway URL at https://www.qualys.com/platform-identification/
    MinLength: 1
  Regions:
    Type: List<String>
    Default: us-east-1
    AllowedValues:
      - us-east-2
      - us-east-1
      - us-west-1
      - us-west-2
      - af-south-1
      - ap-east-1
      - ap-south-2
      - ap-southeast-3
      - ap-southeast-4
      - ap-south-1
      - ap-northeast-3
      - ap-northeast-2
      - ap-southeast-1
      - ap-southeast-2
      - ap-northeast-1
      - ca-central-1
      - ca-west-1
      - eu-central-1
      - eu-west-1
      - eu-west-2
      - eu-south-1
      - eu-west-3
      - eu-south-2
      - eu-north-1
      - eu-central-2
      - il-central-1
      - me-south-1
      - me-central-1
      - sa-east-1
    Description: Enter the EventBridge Deployment Region
